schemaVersion: 2.3.0
metadata:
  name: autosd-quickstart
  tags:
    - rhivos
    - autosd
    - jumpstarter
    - RHAS
components:
  - name: runtime
    container:
      image: ghcr.io/rhadp/codespaces:latest
      memoryLimit: "4Gi"
      memoryRequest: "1Gi"
      cpuLimit: "4"
      cpuRequest: "1"
      mountSources: true
      # environment variables
      #env:
      #  - name: JUMPSTARTER_GRPC_ENDPOINT
      #    value: "grpc.rhadp-jumpstarter.apps.CLUSTER_BASE_DOMAIN"
commands:
  - id: init-workspace
    exec:
      component: runtime
      commandLine: |
        /home/tooling/.scripts/init-workspace
events:
  postStart:
    - init-workspace