FROM ghcr.io/rhadp/codespaces:latest

USER root

ARG TARGETARCH

# install centos stream & fedora repos, other vars
ENV ARCH=${TARGETARCH:-arm64} \
    HOME=/home/tooling \
    XDG_CONFIG_HOME=/home/tooling/.config 

# add your customizations here


# A last pass to make sure that an arbitrary user can write in $HOME
RUN chgrp -R 0 /home && chmod -R g=u /home

USER 10001
ENV HOME=/home/user
WORKDIR /projects