FROM ghcr.io/rhadp/codespaces:latest

USER root

ARG TARGETARCH

# install centos stream & fedora repos, other vars
ENV ARCH=${TARGETARCH:-arm64} \
    XDG_CONFIG_HOME=/home/tooling/.config 

# add your customizations here

# clean up
RUN dnf -y clean all --enablerepo='*' && \
    rm -rf /var/cache/dnf

# Create symbolic links from /home/tooling/ -> /home/user/
#RUN stow . -t /home/user/ -d /home/tooling/ --no-folding

# A last pass to make sure that an arbitrary user can write in $HOME
RUN chgrp -R 0 /home && chmod -R g=u /home

# back to the user
USER 10001